### ISSUE TITLE
parser crashes with additional attributes in other namespace

### ISSUE THREAD

**Issue by crotwell** [anss-sis/extstationxml#2]
IRIS adds extra attributes under their own namespace, which should be legal, but crashes the parser.

For example:
```
iris:alternateNetworkCodes="_CEUSN,.GREG,_US-TA-ADOPTED,_US-REGIONAL,_REALTIME,.UNRESTRICTED"
```

```
owl:2extStationXML crotwell$ python3
Python 3.7.4 (default, Aug 13 2019, 15:17:50)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> import sisxmlparser3_0 as sisxmlparser
>>> staxml = sisxmlparser.parse('testdata/N4_T42B.staxml', isExtStaXml = False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/crotwell/dev/seis/2extStationXML/sisxmlparser3_0.py", line 1405, in parse
    raise SISError(f'Warning: Unknown/unexpected namespace. Prefix:{k}, uri: {uri}')
sisxmlparser3_0.SISError: Warning: Unknown/unexpected namespace. Prefix:iris, uri: http://www.fdsn.org/xml/station/1/iris
```

Changing lines 1402-1405 to this:
```
        if uri in insd:
            docnsprefixmap[k] = insd[uri]
        else:
            docnsprefixmap[k] =k
```
at least allows the parser to run. I am not sure if that is the right way to go as other name space attributes are lost on write.

**Comment by anss-sis** [comment]
The parser prints out a warning message and ignores the elements/attributes from unknown namespaces. These elements will not be written out by the export functions.
